In [1]:
# lbbVIXAnalysis-3
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', None)

import datetime as dt
from dateutil.relativedelta import relativedelta

import os
os.getcwd()

'C:\\Users\\cinderella\\dataSci\\DataScience\\eliteDataScience\\07-CapstoneProject\\Final\\_projectNotebooks'

In [2]:
os.chdir('c:\\users\\cinderella\\datasci\\datascience\\elitedatascience\\07-cornerstoneproject\\Final')

In [3]:
## Now that we know option expiration(opXP) we know futures expiration(t01XP).
## Now we need to determine for a particular trade date for term 01 what was the futures contract
## once we know the front month, we can calculate the contracts for the rest of the term structure
# 
## 
## We start with file of saved option/VX futures information from VIXAnalysis-2-2

In [4]:
df = pd.read_csv('abt-2.csv', index_col = 0)

In [5]:
df.tail(5)

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME
33796,2020-08-17,Z (Dec 2020),28.06,28.10,27.31,27.60,27.375,-0.925,7541,0,18656,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
33797,2020-08-18,Z (Dec 2020),27.40,27.75,27.20,27.42,27.475,0.100,6174,0,19197,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
33798,2020-08-19,Z (Dec 2020),27.40,28.00,27.35,27.92,27.900,0.425,6049,0,20106,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
33799,2020-08-20,Z (Dec 2020),27.92,28.52,27.65,27.80,27.825,-0.075,6803,0,20760,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
33800,2020-08-21,Z (Dec 2020),27.77,28.45,27.66,28.24,28.175,0.350,5035,0,20592,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT

In [6]:
df.loc[(df['Trade Date'] == '2020-08-03')]

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME
2563,2020-08-03,F (Jan 2021),29.00,29.15,28.78,28.95,28.975,0.000,1478,0,7121,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
5717,2020-08-03,G (Feb 2021),28.44,28.65,28.30,28.40,28.475,0.000,548,0,2576,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
8223,2020-08-03,H (Mar 2021),28.45,28.45,28.15,28.31,28.350,-0.050,25,0,314,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
10727,2020-08-03,J (Apr 2021),0.00,26.80,36.90,0.00,29.125,0.175,0,0,0,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
22645,2020-08-03,Q (Aug 2020),26.95,27.30,26.44,26.80,26.775,-0.050,57171,540,113520,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
25205,2020-08-03,U (Sep 2020),29.65,29.97,29.10,29.34,29.375,-0.250,46047,360,82278,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
27870,2020-08-03,V (Oct 2020),32.15,32.42,31.67,31.90,31.850,-0.275,9226,0,30489,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
31181,2020-08-03,X (Nov 2020),30.00,30.24,29.75,29.85,29.875,-0.150,5654,0,24740,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT
33786,2020-08-03,Z (Dec 2020),28.58,28.75,28.34,28.52,28.550,-0.025,2134,0,13403,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT

In [7]:
df.shape

(33792, 28)

In [8]:
df.dtypes

Trade Date        object
Futures           object
Open             float64
High             float64
Low              float64
Close            float64
Settle           float64
Change           float64
Total Volume       int64
EFP                int64
Open Interest      int64
calYear            int64
calMth             int64
opYear             int64
opMth              int64
opFOM             object
opDOW1st           int64
opDOW2nd           int64
noYear             int64
spxDaysNum         int64
opXP              object
opXP_DOW           int64
weekday           object
t01XP             object
LTD               object
dt01              object
dt02              object
LTD-TIME          object
dtype: object

In [9]:
# re-establish datetime vars..csv format doesn't save datetimes (it does preserve numeric formats anc object)
df['Trade Date'] = pd.to_datetime(df['Trade Date'])
df['opFOM'] = pd.to_datetime(df['opFOM'])
df['t01XP'] = pd.to_datetime(df['t01XP'])
df['LTD'] = pd.to_datetime(df['LTD'])
df['dt01'] = pd.to_datetime(df['dt01'])
df['dt02'] = pd.to_datetime(df['dt02'])
df['opXP'] = pd.to_datetime(df['opXP'])

In [10]:
#df['numMthM01'] = np.where(df['LTD']- df['Trade Date']> 0, df['opMth'], df['calMth'])
## this doesn't work because date difference is being compared to an int 
## instead create datediff column

In [11]:
df['diffDates'] = df['LTD'] - df['Trade Date']  
## shows us a zero if the contract has just started/ended
## a negative number means the calendar month does not equal the current futures month
## the negative can be thought of as how many days into the (whatever the next month is from the calendar month) contract
## for example:
## if the trade date is 6/22/2020, the spx next month (7) options expires on Friday 7/17
## therefore the VIX futures (expiring 30 days before the spx Options) expired already on 6/17
## the diffDates says -5 because we are not in the 6th month futures, now the front month contract is July(7th month)
## so on 6/22/2020, we are 5 days into the new front month (term 01) contract of July

In [12]:
## futures months straddle two calendar months, so the futures month dosen't always equal the calendar month 
## (see above)
df['numMthT01'] = np.where(df['diffDates'].dt.days >= 0, df['calMth'], df['opMth'])

In [13]:
df.tail(5)

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME,diffDates,numMthT01
33796,2020-08-17,Z (Dec 2020),28.06,28.10,27.31,27.60,27.375,-0.925,7541,0,18656,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,2 days,8
33797,2020-08-18,Z (Dec 2020),27.40,27.75,27.20,27.42,27.475,0.100,6174,0,19197,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,1 days,8
33798,2020-08-19,Z (Dec 2020),27.40,28.00,27.35,27.92,27.900,0.425,6049,0,20106,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,0 days,8
33799,2020-08-20,Z (Dec 2020),27.92,28.52,27.65,27.80,27.825,-0.075,6803,0,20760,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-1 days,9
33800,2020-08-21,Z (Dec 2020),27.77,28.45,27.66,28.24,28.175,0.350,5035,0,20592,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-2 days,9

In [14]:
d_conMths = {1 : 'F',
              2 : 'G',
              3 : 'H',
              4 : 'J',
              5 : 'K',
              6 : 'M',
              7 : 'N',
              8 : 'Q',
              9 : 'U',
              10 : 'V',
              11 : 'X',
              12 : 'Z'}

In [15]:
d_numMths = {'Jan':1,
            'Feb':2,
            'Mar':3,
            'Apr':4,
            'May':5,
            'Jun':6,
            'Jul':7,
            'Aug':8,
            'Sep':9,
            'Oct':10,
            'Nov':11,
            'Dec':12}

In [16]:
## now that we know the front month we can figure out the remaining term structure (t02 - t09)

In [17]:
df['numMthT02'] = np.where(df['numMthT01'] == 12, 1, df['numMthT01'] + 1)
df['numMthT03'] = np.where(df['numMthT02'] == 12, 1, df['numMthT02'] + 1)
df['numMthT04'] = np.where(df['numMthT03'] == 12, 1, df['numMthT03'] + 1)
df['numMthT05'] = np.where(df['numMthT04'] == 12, 1, df['numMthT04'] + 1)
df['numMthT06'] = np.where(df['numMthT05'] == 12, 1, df['numMthT05'] + 1)
df['numMthT07'] = np.where(df['numMthT06'] == 12, 1, df['numMthT06'] + 1)
df['numMthT08'] = np.where(df['numMthT07'] == 12, 1, df['numMthT07'] + 1)
df['numMthT09'] = np.where(df['numMthT08'] == 12, 1, df['numMthT08'] + 1)
df['numMthT10'] = np.where(df['numMthT09'] == 12, 1, df['numMthT09'] + 1)
df['numMthT11'] = np.where(df['numMthT10'] == 12, 1, df['numMthT10'] + 1)
df['numMthT12'] = np.where(df['numMthT11'] == 12, 1, df['numMthT11'] + 1)

In [18]:
## we are trying to get a column that gives the term position given the trade date and the futures contract,
## so first, we need help on the futures contracts, right now, they are all in a big string object
## lets split them by futAlpha, futMth and futYear.. 'fut' is for futures,

In [19]:
df['Futures'].unique()

array(['F (Jan 2005)', 'F (Jan 2006)', 'F (Jan 2007)', 'F (Jan 2008)',
       'F (Jan 2009)', 'F (Jan 2010)', 'F (Jan 2011)', 'F (Jan 2012)',
       'F (Jan 2013)', 'F (Jan 2014)', 'F (Jan 2015)', 'F (Jan 2016)',
       'F (Jan 2017)', 'F (Jan 2018)', 'F (Jan 2019)', 'F (Jan 2020)',
       'F (Jan 2021)', 'G (Feb 2005)', 'G (Feb 2006)', 'G (Feb 2007)',
       'G (Feb 2008)', 'G (Feb 2009)', 'G (Feb 2010)', 'G (Feb 2011)',
       'G (Feb 2012)', 'G (Feb 2013)', 'G (Feb 2014)', 'G (Feb 2015)',
       'G (Feb 2016)', 'G (Feb 2017)', 'G (Feb 2018)', 'G (Feb 2019)',
       'G (Feb 2020)', 'G (Feb 2021)', 'H (Mar 2005)', 'H (Mar 2006)',
       'H (Mar 2007)', 'H (Mar 2008)', 'H (Mar 2009)', 'H (Mar 2010)',
       'H (Mar 2011)', 'H (Mar 2012)', 'H (Mar 2013)', 'H (Mar 2014)',
       'H (Mar 2015)', 'H (Mar 2016)', 'H (Mar 2017)', 'H (Mar 2018)',
       'H (Mar 2019)', 'H (Mar 2020)', 'H (Mar 2021)', 'J (Apr 2006)',
       'J (Apr 2007)', 'J (Apr 2008)', 'J (Apr 2009)', 'J (Apr 2010)',
       'J (Apr 2011)', 'J (Apr 2012)', 'J (Apr 2013)', 'J (Apr 2014)',
       'J (Apr 2015)', 'J (Apr 2016)', 'J (Apr 2017)', 'J (Apr 2018)',
       'J (Apr 2019)', 'J (Apr 2020)', 'J (Apr 2021)', 'K (May 2004)',
       'K (May 2005)', 'K (May 2006)', 'K (May 2007)', 'K (May 2008)',
       'K (May 2009)', 'K (May 2010)', 'K (May 2011)', 'K (May 2012)',
       'K (May 2013)', 'K (May 2014)', 'K (May 2015)', 'K (May 2016)',
       'K (May 2017)', 'K (May 2018)', 'K (May 2019)', 'K (May 2020)',
       'M (Jun 2004)', 'M (Jun 2005)', 'M (Jun 2006)', 'M (Jun 2007)',
       'M (Jun 2008)', 'M (Jun 2009)', 'M (Jun 2010)', 'M (Jun 2011)',
       'M (Jun 2012)', 'M (Jun 2013)', 'M (Jun 2014)', 'M (Jun 2015)',
       'M (Jun 2016)', 'M (Jun 2017)', 'M (Jun 2018)', 'M (Jun 2019)',
       'M (Jun 2020)', 'N (Jul 2004)', 'N (Jul 2006)', 'N (Jul 2007)',
       'N (Jul 2008)', 'N (Jul 2009)', 'N (Jul 2010)', 'N (Jul 2011)',
       'N (Jul 2012)', 'N (Jul 2013)', 'N (Jul 2014)', 'N (Jul 2015)',
       'N (Jul 2016)', 'N (Jul 2017)', 'N (Jul 2018)', 'N (Jul 2019)',
       'N (Jul 2020)', 'Q (Aug 2004)', 'Q (Aug 2005)', 'Q (Aug 2006)',
       'Q (Aug 2007)', 'Q (Aug 2008)', 'Q (Aug 2009)', 'Q (Aug 2010)',
       'Q (Aug 2011)', 'Q (Aug 2012)', 'Q (Aug 2013)', 'Q (Aug 2014)',
       'Q (Aug 2015)', 'Q (Aug 2016)', 'Q (Aug 2017)', 'Q (Aug 2018)',
       'Q (Aug 2019)', 'Q (Aug 2020)', 'U (Sep 2004)', 'U (Sep 2006)',
       'U (Sep 2007)', 'U (Sep 2008)', 'U (Sep 2009)', 'U (Sep 2010)',
       'U (Sep 2011)', 'U (Sep 2012)', 'U (Sep 2013)', 'U (Sep 2014)',
       'U (Sep 2015)', 'U (Sep 2016)', 'U (Sep 2017)', 'U (Sep 2018)',
       'U (Sep 2019)', 'U (Sep 2020)', 'V (Oct 2004)', 'V (Oct 2005)',
       'V (Oct 2006)', 'V (Oct 2007)', 'V (Oct 2008)', 'V (Oct 2009)',
       'V (Oct 2010)', 'V (Oct 2011)', 'V (Oct 2012)', 'V (Oct 2013)',
       'V (Oct 2014)', 'V (Oct 2015)', 'V (Oct 2016)', 'V (Oct 2017)',
       'V (Oct 2018)', 'V (Oct 2019)', 'V (Oct 2020)', 'X (Nov 2004)',
       'X (Nov 2005)', 'X (Nov 2006)', 'X (Nov 2007)', 'X (Nov 2008)',
       'X (Nov 2009)', 'X (Nov 2010)', 'X (Nov 2011)', 'X (Nov 2012)',
       'X (Nov 2013)', 'X (Nov 2014)', 'X (Nov 2015)', 'X (Nov 2016)',
       'X (Nov 2017)', 'X (Nov 2018)', 'X (Nov 2019)', 'X (Nov 2020)',
       'Z (Dec 2005)', 'Z (Dec 2006)', 'Z (Dec 2007)', 'Z (Dec 2008)',
       'Z (Dec 2009)', 'Z (Dec 2010)', 'Z (Dec 2011)', 'Z (Dec 2012)',
       'Z (Dec 2013)', 'Z (Dec 2014)', 'Z (Dec 2015)', 'Z (Dec 2016)',
       'Z (Dec 2017)', 'Z (Dec 2018)', 'Z (Dec 2019)', 'Z (Dec 2020)'],
      dtype=object)

In [20]:
df.tail(5)

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME,diffDates,numMthT01,numMthT02,numMthT03,numMthT04,numMthT05,numMthT06,numMthT07,numMthT08,numMthT09,numMthT10,numMthT11,numMthT12
33796,2020-08-17,Z (Dec 2020),28.06,28.10,27.31,27.60,27.375,-0.925,7541,0,18656,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,2 days,8,9,10,11,12,1,2,3,4,5,6,7
33797,2020-08-18,Z (Dec 2020),27.40,27.75,27.20,27.42,27.475,0.100,6174,0,19197,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,1 days,8,9,10,11,12,1,2,3,4,5,6,7
33798,2020-08-19,Z (Dec 2020),27.40,28.00,27.35,27.92,27.900,0.425,6049,0,20106,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,0 days,8,9,10,11,12,1,2,3,4,5,6,7
33799,2020-08-20,Z (Dec 2020),27.92,28.52,27.65,27.80,27.825,-0.075,6803,0,20760,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-1 days,9,10,11,12,1,2,3,4,5,6,7,8
33800,2020-08-21,Z (Dec 2020),27.77,28.45,27.66,28.24,28.175,0.350,5035,0,20592,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-2 days,9,10,11,12,1,2,3,4,5,6,7,8

In [21]:
df.dtypes

Trade Date        datetime64[ns]
Futures                   object
Open                     float64
High                     float64
Low                      float64
Close                    float64
Settle                   float64
Change                   float64
Total Volume               int64
EFP                        int64
Open Interest              int64
calYear                    int64
calMth                     int64
opYear                     int64
opMth                      int64
opFOM             datetime64[ns]
opDOW1st                   int64
opDOW2nd                   int64
noYear                     int64
spxDaysNum                 int64
opXP              datetime64[ns]
opXP_DOW                   int64
weekday                   object
t01XP             datetime64[ns]
LTD               datetime64[ns]
dt01              datetime64[ns]
dt02              datetime64[ns]
LTD-TIME                  object
diffDates        timedelta64[ns]
numMthT01                  int64
numMthT02                  int64
numMthT03                  int64
numMthT04                  int64
numMthT05                  int64
numMthT06                  int64
numMthT07                  int64
numMthT08                  int64
numMthT09                  int64
numMthT10                  int64
numMthT11                  int64
numMthT12                  int64
dtype: object

In [22]:
#sub_mths9 = relativedelta(months=-6)
df['9MthsStart'] = (df['t01XP'] - dt.timedelta(days=270))## added 7/17/2020
df['7MthsStart'] = (df['t01XP'] - dt.timedelta(days=210))## added 7/17/2020

In [23]:
## Split out the futures text only after making it consistent..which I didn't realize until later
df[['futAlpha', 'futMthName','futYear']] = df.Futures.str.split(" ", expand = True)

In [24]:
df.tail(5)

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME,diffDates,numMthT01,numMthT02,numMthT03,numMthT04,numMthT05,numMthT06,numMthT07,numMthT08,numMthT09,numMthT10,numMthT11,numMthT12,9MthsStart,7MthsStart,futAlpha,futMthName,futYear
33796,2020-08-17,Z (Dec 2020),28.06,28.10,27.31,27.60,27.375,-0.925,7541,0,18656,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,2 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,(Dec,2020)
33797,2020-08-18,Z (Dec 2020),27.40,27.75,27.20,27.42,27.475,0.100,6174,0,19197,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,1 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,(Dec,2020)
33798,2020-08-19,Z (Dec 2020),27.40,28.00,27.35,27.92,27.900,0.425,6049,0,20106,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,0 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,(Dec,2020)
33799,2020-08-20,Z (Dec 2020),27.92,28.52,27.65,27.80,27.825,-0.075,6803,0,20760,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-1 days,9,10,11,12,1,2,3,4,5,6,7,8,2019-11-23,2020-01-22,Z,(Dec,2020)
33800,2020-08-21,Z (Dec 2020),27.77,28.45,27.66,28.24,28.175,0.350,5035,0,20592,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-2 days,9,10,11,12,1,2,3,4,5,6,7,8,2019-11-23,2020-01-22,Z,(Dec,2020)

In [25]:
# trim the strings in conMth and conYear of parenthesis
df['futMthName'] = df['futMthName'].str.replace("(","")

In [26]:
df['futYear'] = df['futYear'].str.replace(")","")

In [27]:
df.tail(5)

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME,diffDates,numMthT01,numMthT02,numMthT03,numMthT04,numMthT05,numMthT06,numMthT07,numMthT08,numMthT09,numMthT10,numMthT11,numMthT12,9MthsStart,7MthsStart,futAlpha,futMthName,futYear
33796,2020-08-17,Z (Dec 2020),28.06,28.10,27.31,27.60,27.375,-0.925,7541,0,18656,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,2 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,Dec,2020
33797,2020-08-18,Z (Dec 2020),27.40,27.75,27.20,27.42,27.475,0.100,6174,0,19197,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,1 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,Dec,2020
33798,2020-08-19,Z (Dec 2020),27.40,28.00,27.35,27.92,27.900,0.425,6049,0,20106,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,0 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,Dec,2020
33799,2020-08-20,Z (Dec 2020),27.92,28.52,27.65,27.80,27.825,-0.075,6803,0,20760,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-1 days,9,10,11,12,1,2,3,4,5,6,7,8,2019-11-23,2020-01-22,Z,Dec,2020
33800,2020-08-21,Z (Dec 2020),27.77,28.45,27.66,28.24,28.175,0.350,5035,0,20592,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-2 days,9,10,11,12,1,2,3,4,5,6,7,8,2019-11-23,2020-01-22,Z,Dec,2020

In [28]:
## compute the futMthnum instead of the futMthName like we have
df['futMth'] = df['futMthName'].map(d_numMths)

In [29]:
df.tail(5)

,Trade Date,Futures,Open,High,Low,Close,Settle,Change,Total Volume,EFP,Open Interest,calYear,calMth,opYear,opMth,opFOM,opDOW1st,opDOW2nd,noYear,spxDaysNum,opXP,opXP_DOW,weekday,t01XP,LTD,dt01,dt02,LTD-TIME,diffDates,numMthT01,numMthT02,numMthT03,numMthT04,numMthT05,numMthT06,numMthT07,numMthT08,numMthT09,numMthT10,numMthT11,numMthT12,9MthsStart,7MthsStart,futAlpha,futMthName,futYear,futMth
33796,2020-08-17,Z (Dec 2020),28.06,28.10,27.31,27.60,27.375,-0.925,7541,0,18656,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,2 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,Dec,2020,12
33797,2020-08-18,Z (Dec 2020),27.40,27.75,27.20,27.42,27.475,0.100,6174,0,19197,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,1 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,Dec,2020,12
33798,2020-08-19,Z (Dec 2020),27.40,28.00,27.35,27.92,27.900,0.425,6049,0,20106,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,0 days,8,9,10,11,12,1,2,3,4,5,6,7,2019-11-23,2020-01-22,Z,Dec,2020,12
33799,2020-08-20,Z (Dec 2020),27.92,28.52,27.65,27.80,27.825,-0.075,6803,0,20760,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-1 days,9,10,11,12,1,2,3,4,5,6,7,8,2019-11-23,2020-01-22,Z,Dec,2020,12
33800,2020-08-21,Z (Dec 2020),27.77,28.45,27.66,28.24,28.175,0.350,5035,0,20592,2020,8,2020,9,2020-09-01,1,3,0,17,2020-09-18,4,Friday,2020-08-19,2020-08-19,2014-10-22,2015-10-21,8:00 AM CT,-2 days,9,10,11,12,1,2,3,4,5,6,7,8,2019-11-23,2020-01-22,Z,Dec,2020,12

In [32]:
df.to_csv('abt-3.csv')